arrowParens: avoid
bracketSpacing: true
endOfLine: auto
printWidth: 120
singleQuote: false
tabWidth: 2
trailingComma: all

overrides:
  - files: "*.sol"
    options:
      plugins:
        - "prettier-plugin-solidity"
      tabWidth: 4
  - files: "*.ts"
    options:
      parser: "typescript"
