name: "CI"

env:
  CI: true
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7

      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: "actions/setup-node@v3"
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: "Install the dependencies"
        run: "pnpm install --frozen-lockfile"

      - name: "Compile the contracts and generate the TypeChain bindings"
        run: "pnpm build"

      - name: "Test the contracts and generate the coverage report"
        run: "pnpm coverage"

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
